CREATE TYPE "public"."character_mythic_kill_parse_state" AS ENUM('available', 'not_applicable', 'unavailable');--> statement-breakpoint
ALTER TABLE "character_evidence_runs" ADD COLUMN "parse_limitation_code" text;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD COLUMN "damage_parse_state" character_mythic_kill_parse_state DEFAULT 'unavailable' NOT NULL;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD COLUMN "damage_percentile" double precision;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD COLUMN "healing_parse_state" character_mythic_kill_parse_state DEFAULT 'unavailable' NOT NULL;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD COLUMN "healing_percentile" double precision;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD COLUMN "boss_damage_parse_state" character_mythic_kill_parse_state DEFAULT 'unavailable' NOT NULL;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD COLUMN "boss_damage_percentile" double precision;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ALTER COLUMN "damage_parse_state" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ALTER COLUMN "healing_parse_state" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ALTER COLUMN "boss_damage_parse_state" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "character_evidence_runs" ADD CONSTRAINT "character_evidence_runs_completion_limitations_check" CHECK (("character_evidence_runs"."status" = 'complete' AND "character_evidence_runs"."limitation_code" IS NULL AND "character_evidence_runs"."parse_limitation_code" IS NULL) OR ("character_evidence_runs"."status" = 'partial' AND ("character_evidence_runs"."limitation_code" IS NOT NULL OR "character_evidence_runs"."parse_limitation_code" IS NOT NULL)) OR "character_evidence_runs"."status" NOT IN ('complete', 'partial'));--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD CONSTRAINT "character_mythic_kills_damage_parse_check" CHECK (("character_mythic_kills"."damage_parse_state" = 'available' AND "character_mythic_kills"."damage_percentile" IS NOT NULL AND "character_mythic_kills"."damage_percentile" >= 0 AND "character_mythic_kills"."damage_percentile" <= 100) OR ("character_mythic_kills"."damage_parse_state" IN ('not_applicable', 'unavailable') AND "character_mythic_kills"."damage_percentile" IS NULL));--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD CONSTRAINT "character_mythic_kills_healing_parse_check" CHECK (("character_mythic_kills"."healing_parse_state" = 'available' AND "character_mythic_kills"."healing_percentile" IS NOT NULL AND "character_mythic_kills"."healing_percentile" >= 0 AND "character_mythic_kills"."healing_percentile" <= 100) OR ("character_mythic_kills"."healing_parse_state" IN ('not_applicable', 'unavailable') AND "character_mythic_kills"."healing_percentile" IS NULL));--> statement-breakpoint
ALTER TABLE "character_mythic_kills" ADD CONSTRAINT "character_mythic_kills_boss_damage_parse_check" CHECK (("character_mythic_kills"."boss_damage_parse_state" = 'available' AND "character_mythic_kills"."boss_damage_percentile" IS NOT NULL AND "character_mythic_kills"."boss_damage_percentile" >= 0 AND "character_mythic_kills"."boss_damage_percentile" <= 100) OR ("character_mythic_kills"."boss_damage_parse_state" IN ('not_applicable', 'unavailable') AND "character_mythic_kills"."boss_damage_percentile" IS NULL));
